// Generated by scripts/build-thread-icons.mjs from chat/thread-icons.mjs. Do not edit.
import type { ComponentType } from 'react'
import I0 from '@tabler/icons-react/dist/esm/icons/IconMessage.mjs'
import I1 from '@tabler/icons-react/dist/esm/icons/IconMessages.mjs'
import I2 from '@tabler/icons-react/dist/esm/icons/IconBulb.mjs'
import I3 from '@tabler/icons-react/dist/esm/icons/IconQuestionMark.mjs'
import I4 from '@tabler/icons-react/dist/esm/icons/IconPencil.mjs'
import I5 from '@tabler/icons-react/dist/esm/icons/IconWriting.mjs'
import I6 from '@tabler/icons-react/dist/esm/icons/IconNotebook.mjs'
import I7 from '@tabler/icons-react/dist/esm/icons/IconBook.mjs'
import I8 from '@tabler/icons-react/dist/esm/icons/IconBooks.mjs'
import I9 from '@tabler/icons-react/dist/esm/icons/IconNews.mjs'
import I10 from '@tabler/icons-react/dist/esm/icons/IconArticle.mjs'
import I11 from '@tabler/icons-react/dist/esm/icons/IconQuote.mjs'
import I12 from '@tabler/icons-react/dist/esm/icons/IconLanguage.mjs'
import I13 from '@tabler/icons-react/dist/esm/icons/IconMail.mjs'
import I14 from '@tabler/icons-react/dist/esm/icons/IconSend.mjs'
import I15 from '@tabler/icons-react/dist/esm/icons/IconPhone.mjs'
import I16 from '@tabler/icons-react/dist/esm/icons/IconSpeakerphone.mjs'
import I17 from '@tabler/icons-react/dist/esm/icons/IconMicrophone.mjs'
import I18 from '@tabler/icons-react/dist/esm/icons/IconClipboardText.mjs'
import I19 from '@tabler/icons-react/dist/esm/icons/IconNotes.mjs'
import I20 from '@tabler/icons-react/dist/esm/icons/IconChecklist.mjs'
import I21 from '@tabler/icons-react/dist/esm/icons/IconListCheck.mjs'
import I22 from '@tabler/icons-react/dist/esm/icons/IconCalendar.mjs'
import I23 from '@tabler/icons-react/dist/esm/icons/IconCalendarEvent.mjs'
import I24 from '@tabler/icons-react/dist/esm/icons/IconClock.mjs'
import I25 from '@tabler/icons-react/dist/esm/icons/IconAlarm.mjs'
import I26 from '@tabler/icons-react/dist/esm/icons/IconHourglass.mjs'
import I27 from '@tabler/icons-react/dist/esm/icons/IconTarget.mjs'
import I28 from '@tabler/icons-react/dist/esm/icons/IconFlag.mjs'
import I29 from '@tabler/icons-react/dist/esm/icons/IconTrophy.mjs'
import I30 from '@tabler/icons-react/dist/esm/icons/IconBriefcase.mjs'
import I31 from '@tabler/icons-react/dist/esm/icons/IconBuilding.mjs'
import I32 from '@tabler/icons-react/dist/esm/icons/IconBuildingStore.mjs'
import I33 from '@tabler/icons-react/dist/esm/icons/IconPresentation.mjs'
import I34 from '@tabler/icons-react/dist/esm/icons/IconChartBar.mjs'
import I35 from '@tabler/icons-react/dist/esm/icons/IconChartLine.mjs'
import I36 from '@tabler/icons-react/dist/esm/icons/IconChartPie.mjs'
import I37 from '@tabler/icons-react/dist/esm/icons/IconReportAnalytics.mjs'
import I38 from '@tabler/icons-react/dist/esm/icons/IconTable.mjs'
import I39 from '@tabler/icons-react/dist/esm/icons/IconFileSpreadsheet.mjs'
import I40 from '@tabler/icons-react/dist/esm/icons/IconFileText.mjs'
import I41 from '@tabler/icons-react/dist/esm/icons/IconFiles.mjs'
import I42 from '@tabler/icons-react/dist/esm/icons/IconFolder.mjs'
import I43 from '@tabler/icons-react/dist/esm/icons/IconArchive.mjs'
import I44 from '@tabler/icons-react/dist/esm/icons/IconInbox.mjs'
import I45 from '@tabler/icons-react/dist/esm/icons/IconStack2.mjs'
import I46 from '@tabler/icons-react/dist/esm/icons/IconAdjustments.mjs'
import I47 from '@tabler/icons-react/dist/esm/icons/IconSettings.mjs'
import I48 from '@tabler/icons-react/dist/esm/icons/IconTool.mjs'
import I49 from '@tabler/icons-react/dist/esm/icons/IconTools.mjs'
import I50 from '@tabler/icons-react/dist/esm/icons/IconUsers.mjs'
import I51 from '@tabler/icons-react/dist/esm/icons/IconUser.mjs'
import I52 from '@tabler/icons-react/dist/esm/icons/IconUsersGroup.mjs'
import I53 from '@tabler/icons-react/dist/esm/icons/IconHeartHandshake.mjs'
import I54 from '@tabler/icons-react/dist/esm/icons/IconSchool.mjs'
import I55 from '@tabler/icons-react/dist/esm/icons/IconCertificate.mjs'
import I56 from '@tabler/icons-react/dist/esm/icons/IconGavel.mjs'
import I57 from '@tabler/icons-react/dist/esm/icons/IconScale.mjs'
import I58 from '@tabler/icons-react/dist/esm/icons/IconShieldCheck.mjs'
import I59 from '@tabler/icons-react/dist/esm/icons/IconCoin.mjs'
import I60 from '@tabler/icons-react/dist/esm/icons/IconCash.mjs'
import I61 from '@tabler/icons-react/dist/esm/icons/IconCreditCard.mjs'
import I62 from '@tabler/icons-react/dist/esm/icons/IconReceipt.mjs'
import I63 from '@tabler/icons-react/dist/esm/icons/IconReceiptTax.mjs'
import I64 from '@tabler/icons-react/dist/esm/icons/IconPigMoney.mjs'
import I65 from '@tabler/icons-react/dist/esm/icons/IconWallet.mjs'
import I66 from '@tabler/icons-react/dist/esm/icons/IconChartCandle.mjs'
import I67 from '@tabler/icons-react/dist/esm/icons/IconBusinessplan.mjs'
import I68 from '@tabler/icons-react/dist/esm/icons/IconShoppingCart.mjs'
import I69 from '@tabler/icons-react/dist/esm/icons/IconShoppingBag.mjs'
import I70 from '@tabler/icons-react/dist/esm/icons/IconGift.mjs'
import I71 from '@tabler/icons-react/dist/esm/icons/IconTag.mjs'
import I72 from '@tabler/icons-react/dist/esm/icons/IconDiscount.mjs'
import I73 from '@tabler/icons-react/dist/esm/icons/IconBuildingBank.mjs'
import I74 from '@tabler/icons-react/dist/esm/icons/IconPackage.mjs'
import I75 from '@tabler/icons-react/dist/esm/icons/IconTruckDelivery.mjs'
import I76 from '@tabler/icons-react/dist/esm/icons/IconDiamond.mjs'
import I77 from '@tabler/icons-react/dist/esm/icons/IconCode.mjs'
import I78 from '@tabler/icons-react/dist/esm/icons/IconTerminal2.mjs'
import I79 from '@tabler/icons-react/dist/esm/icons/IconBug.mjs'
import I80 from '@tabler/icons-react/dist/esm/icons/IconGitBranch.mjs'
import I81 from '@tabler/icons-react/dist/esm/icons/IconGitPullRequest.mjs'
import I82 from '@tabler/icons-react/dist/esm/icons/IconBrandGithub.mjs'
import I83 from '@tabler/icons-react/dist/esm/icons/IconApi.mjs'
import I84 from '@tabler/icons-react/dist/esm/icons/IconDatabase.mjs'
import I85 from '@tabler/icons-react/dist/esm/icons/IconServer.mjs'
import I86 from '@tabler/icons-react/dist/esm/icons/IconCloud.mjs'
import I87 from '@tabler/icons-react/dist/esm/icons/IconCpu.mjs'
import I88 from '@tabler/icons-react/dist/esm/icons/IconDeviceDesktop.mjs'
import I89 from '@tabler/icons-react/dist/esm/icons/IconDeviceLaptop.mjs'
import I90 from '@tabler/icons-react/dist/esm/icons/IconDeviceMobile.mjs'
import I91 from '@tabler/icons-react/dist/esm/icons/IconDeviceTablet.mjs'
import I92 from '@tabler/icons-react/dist/esm/icons/IconDeviceWatch.mjs'
import I93 from '@tabler/icons-react/dist/esm/icons/IconWifi.mjs'
import I94 from '@tabler/icons-react/dist/esm/icons/IconRouter.mjs'
import I95 from '@tabler/icons-react/dist/esm/icons/IconLock.mjs'
import I96 from '@tabler/icons-react/dist/esm/icons/IconKey.mjs'
import I97 from '@tabler/icons-react/dist/esm/icons/IconShield.mjs'
import I98 from '@tabler/icons-react/dist/esm/icons/IconRobot.mjs'
import I99 from '@tabler/icons-react/dist/esm/icons/IconBrain.mjs'
import I100 from '@tabler/icons-react/dist/esm/icons/IconHeadset.mjs'
import I101 from '@tabler/icons-react/dist/esm/icons/IconSparkles.mjs'
import I102 from '@tabler/icons-react/dist/esm/icons/IconWand.mjs'
import I103 from '@tabler/icons-react/dist/esm/icons/IconPuzzle.mjs'
import I104 from '@tabler/icons-react/dist/esm/icons/IconPlug.mjs'
import I105 from '@tabler/icons-react/dist/esm/icons/IconWorld.mjs'
import I106 from '@tabler/icons-react/dist/esm/icons/IconWorldWww.mjs'
import I107 from '@tabler/icons-react/dist/esm/icons/IconLink.mjs'
import I108 from '@tabler/icons-react/dist/esm/icons/IconPhoto.mjs'
import I109 from '@tabler/icons-react/dist/esm/icons/IconCamera.mjs'
import I110 from '@tabler/icons-react/dist/esm/icons/IconVideo.mjs'
import I111 from '@tabler/icons-react/dist/esm/icons/IconMovie.mjs'
import I112 from '@tabler/icons-react/dist/esm/icons/IconPalette.mjs'
import I113 from '@tabler/icons-react/dist/esm/icons/IconBrush.mjs'
import I114 from '@tabler/icons-react/dist/esm/icons/IconTypography.mjs'
import I115 from '@tabler/icons-react/dist/esm/icons/IconLayout.mjs'
import I116 from '@tabler/icons-react/dist/esm/icons/IconColorSwatch.mjs'
import I117 from '@tabler/icons-react/dist/esm/icons/IconVector.mjs'
import I118 from '@tabler/icons-react/dist/esm/icons/IconBike.mjs'
import I119 from '@tabler/icons-react/dist/esm/icons/IconRun.mjs'
import I120 from '@tabler/icons-react/dist/esm/icons/IconWalk.mjs'
import I121 from '@tabler/icons-react/dist/esm/icons/IconBarbell.mjs'
import I122 from '@tabler/icons-react/dist/esm/icons/IconSwimming.mjs'
import I123 from '@tabler/icons-react/dist/esm/icons/IconYoga.mjs'
import I124 from '@tabler/icons-react/dist/esm/icons/IconStretching.mjs'
import I125 from '@tabler/icons-react/dist/esm/icons/IconTrekking.mjs'
import I126 from '@tabler/icons-react/dist/esm/icons/IconMountain.mjs'
import I127 from '@tabler/icons-react/dist/esm/icons/IconBallFootball.mjs'
import I128 from '@tabler/icons-react/dist/esm/icons/IconBallBasketball.mjs'
import I129 from '@tabler/icons-react/dist/esm/icons/IconBallTennis.mjs'
import I130 from '@tabler/icons-react/dist/esm/icons/IconGolf.mjs'
import I131 from '@tabler/icons-react/dist/esm/icons/IconHeartbeat.mjs'
import I132 from '@tabler/icons-react/dist/esm/icons/IconHeart.mjs'
import I133 from '@tabler/icons-react/dist/esm/icons/IconStethoscope.mjs'
import I134 from '@tabler/icons-react/dist/esm/icons/IconPill.mjs'
import I135 from '@tabler/icons-react/dist/esm/icons/IconDental.mjs'
import I136 from '@tabler/icons-react/dist/esm/icons/IconEye.mjs'
import I137 from '@tabler/icons-react/dist/esm/icons/IconBed.mjs'
import I138 from '@tabler/icons-react/dist/esm/icons/IconMoon.mjs'
import I139 from '@tabler/icons-react/dist/esm/icons/IconZzz.mjs'
import I140 from '@tabler/icons-react/dist/esm/icons/IconScaleOutline.mjs'
import I141 from '@tabler/icons-react/dist/esm/icons/IconApple.mjs'
import I142 from '@tabler/icons-react/dist/esm/icons/IconSalad.mjs'
import I143 from '@tabler/icons-react/dist/esm/icons/IconDroplet.mjs'
import I144 from '@tabler/icons-react/dist/esm/icons/IconMoodSmile.mjs'
import I145 from '@tabler/icons-react/dist/esm/icons/IconMoodSad.mjs'
import I146 from '@tabler/icons-react/dist/esm/icons/IconLeaf.mjs'
import I147 from '@tabler/icons-react/dist/esm/icons/IconFlower.mjs'
import I148 from '@tabler/icons-react/dist/esm/icons/IconToolsKitchen2.mjs'
import I149 from '@tabler/icons-react/dist/esm/icons/IconChefHat.mjs'
import I150 from '@tabler/icons-react/dist/esm/icons/IconCoffee.mjs'
import I151 from '@tabler/icons-react/dist/esm/icons/IconCup.mjs'
import I152 from '@tabler/icons-react/dist/esm/icons/IconBeer.mjs'
import I153 from '@tabler/icons-react/dist/esm/icons/IconGlassFull.mjs'
import I154 from '@tabler/icons-react/dist/esm/icons/IconPizza.mjs'
import I155 from '@tabler/icons-react/dist/esm/icons/IconCake.mjs'
import I156 from '@tabler/icons-react/dist/esm/icons/IconBread.mjs'
import I157 from '@tabler/icons-react/dist/esm/icons/IconEgg.mjs'
import I158 from '@tabler/icons-react/dist/esm/icons/IconFish.mjs'
import I159 from '@tabler/icons-react/dist/esm/icons/IconMeat.mjs'
import I160 from '@tabler/icons-react/dist/esm/icons/IconCarrot.mjs'
import I161 from '@tabler/icons-react/dist/esm/icons/IconHome.mjs'
import I162 from '@tabler/icons-react/dist/esm/icons/IconSofa.mjs'
import I163 from '@tabler/icons-react/dist/esm/icons/IconArmchair.mjs'
import I164 from '@tabler/icons-react/dist/esm/icons/IconBath.mjs'
import I165 from '@tabler/icons-react/dist/esm/icons/IconWashMachine.mjs'
import I166 from '@tabler/icons-react/dist/esm/icons/IconBulbFilled.mjs'
import I167 from '@tabler/icons-react/dist/esm/icons/IconPlant.mjs'
import I168 from '@tabler/icons-react/dist/esm/icons/IconPlant2.mjs'
import I169 from '@tabler/icons-react/dist/esm/icons/IconTree.mjs'
import I170 from '@tabler/icons-react/dist/esm/icons/IconShovel.mjs'
import I171 from '@tabler/icons-react/dist/esm/icons/IconHammer.mjs'
import I172 from '@tabler/icons-react/dist/esm/icons/IconPaint.mjs'
import I173 from '@tabler/icons-react/dist/esm/icons/IconRuler.mjs'
import I174 from '@tabler/icons-react/dist/esm/icons/IconTrash.mjs'
import I175 from '@tabler/icons-react/dist/esm/icons/IconRecycle.mjs'
import I176 from '@tabler/icons-react/dist/esm/icons/IconDog.mjs'
import I177 from '@tabler/icons-react/dist/esm/icons/IconCat.mjs'
import I178 from '@tabler/icons-react/dist/esm/icons/IconPaw.mjs'
import I179 from '@tabler/icons-react/dist/esm/icons/IconBabyCarriage.mjs'
import I180 from '@tabler/icons-react/dist/esm/icons/IconShirt.mjs'
import I181 from '@tabler/icons-react/dist/esm/icons/IconHanger.mjs'
import I182 from '@tabler/icons-react/dist/esm/icons/IconPlane.mjs'
import I183 from '@tabler/icons-react/dist/esm/icons/IconCar.mjs'
import I184 from '@tabler/icons-react/dist/esm/icons/IconBus.mjs'
import I185 from '@tabler/icons-react/dist/esm/icons/IconTrain.mjs'
import I186 from '@tabler/icons-react/dist/esm/icons/IconShip.mjs'
import I187 from '@tabler/icons-react/dist/esm/icons/IconGasStation.mjs'
import I188 from '@tabler/icons-react/dist/esm/icons/IconMap.mjs'
import I189 from '@tabler/icons-react/dist/esm/icons/IconMapPin.mjs'
import I190 from '@tabler/icons-react/dist/esm/icons/IconRoute.mjs'
import I191 from '@tabler/icons-react/dist/esm/icons/IconCompass.mjs'
import I192 from '@tabler/icons-react/dist/esm/icons/IconTent.mjs'
import I193 from '@tabler/icons-react/dist/esm/icons/IconBeach.mjs'
import I194 from '@tabler/icons-react/dist/esm/icons/IconLuggage.mjs'
import I195 from '@tabler/icons-react/dist/esm/icons/IconEPassport.mjs'
import I196 from '@tabler/icons-react/dist/esm/icons/IconBuildingSkyscraper.mjs'
import I197 from '@tabler/icons-react/dist/esm/icons/IconRoad.mjs'
import I198 from '@tabler/icons-react/dist/esm/icons/IconParking.mjs'
import I199 from '@tabler/icons-react/dist/esm/icons/IconSteeringWheel.mjs'
import I200 from '@tabler/icons-react/dist/esm/icons/IconMotorbike.mjs'
import I201 from '@tabler/icons-react/dist/esm/icons/IconScooter.mjs'
import I202 from '@tabler/icons-react/dist/esm/icons/IconSun.mjs'
import I203 from '@tabler/icons-react/dist/esm/icons/IconCloudRain.mjs'
import I204 from '@tabler/icons-react/dist/esm/icons/IconSnowflake.mjs'
import I205 from '@tabler/icons-react/dist/esm/icons/IconUmbrella.mjs'
import I206 from '@tabler/icons-react/dist/esm/icons/IconTemperature.mjs'
import I207 from '@tabler/icons-react/dist/esm/icons/IconWind.mjs'
import I208 from '@tabler/icons-react/dist/esm/icons/IconFlame.mjs'
import I209 from '@tabler/icons-react/dist/esm/icons/IconBolt.mjs'
import I210 from '@tabler/icons-react/dist/esm/icons/IconPlanet.mjs'
import I211 from '@tabler/icons-react/dist/esm/icons/IconTelescope.mjs'
import I212 from '@tabler/icons-react/dist/esm/icons/IconMusic.mjs'
import I213 from '@tabler/icons-react/dist/esm/icons/IconHeadphones.mjs'
import I214 from '@tabler/icons-react/dist/esm/icons/IconGuitarPick.mjs'
import I215 from '@tabler/icons-react/dist/esm/icons/IconDeviceGamepad2.mjs'
import I216 from '@tabler/icons-react/dist/esm/icons/IconDice.mjs'
import I217 from '@tabler/icons-react/dist/esm/icons/IconChess.mjs'
import I218 from '@tabler/icons-react/dist/esm/icons/IconConfetti.mjs'
import I219 from '@tabler/icons-react/dist/esm/icons/IconBalloon.mjs'
import I220 from '@tabler/icons-react/dist/esm/icons/IconTicket.mjs'
import I221 from '@tabler/icons-react/dist/esm/icons/IconMasksTheater.mjs'
import I222 from '@tabler/icons-react/dist/esm/icons/IconMicrophone2.mjs'
import I223 from '@tabler/icons-react/dist/esm/icons/IconBrandYoutube.mjs'
import I224 from '@tabler/icons-react/dist/esm/icons/IconBrandSpotify.mjs'
import I225 from '@tabler/icons-react/dist/esm/icons/IconDeviceTv.mjs'
import I226 from '@tabler/icons-react/dist/esm/icons/IconBook2.mjs'
import I227 from '@tabler/icons-react/dist/esm/icons/IconPokeball.mjs'
import I228 from '@tabler/icons-react/dist/esm/icons/IconCards.mjs'
import I229 from '@tabler/icons-react/dist/esm/icons/IconPuzzle2.mjs'
import I230 from '@tabler/icons-react/dist/esm/icons/IconFlask.mjs'
import I231 from '@tabler/icons-react/dist/esm/icons/IconAtom.mjs'
import I232 from '@tabler/icons-react/dist/esm/icons/IconDna.mjs'
import I233 from '@tabler/icons-react/dist/esm/icons/IconMath.mjs'
import I234 from '@tabler/icons-react/dist/esm/icons/IconCalculator.mjs'
import I235 from '@tabler/icons-react/dist/esm/icons/IconAbacus.mjs'
import I236 from '@tabler/icons-react/dist/esm/icons/IconMicroscope.mjs'
import I237 from '@tabler/icons-react/dist/esm/icons/IconGlobe.mjs'
import I238 from '@tabler/icons-react/dist/esm/icons/IconHistory.mjs'
import I239 from '@tabler/icons-react/dist/esm/icons/IconInfinity.mjs'
import I240 from '@tabler/icons-react/dist/esm/icons/IconAlertTriangle.mjs'
import I241 from '@tabler/icons-react/dist/esm/icons/IconInfoCircle.mjs'
import I242 from '@tabler/icons-react/dist/esm/icons/IconSearch.mjs'
import I243 from '@tabler/icons-react/dist/esm/icons/IconStar.mjs'
import I244 from '@tabler/icons-react/dist/esm/icons/IconBookmark.mjs'
import I245 from '@tabler/icons-react/dist/esm/icons/IconPin.mjs'
import I246 from '@tabler/icons-react/dist/esm/icons/IconBell.mjs'
import I247 from '@tabler/icons-react/dist/esm/icons/IconCalendarHeart.mjs'
import I248 from '@tabler/icons-react/dist/esm/icons/IconCakeRoll.mjs'
import I249 from '@tabler/icons-react/dist/esm/icons/IconChristmasTree.mjs'

export const THREAD_ICONS: Record<string, ComponentType<any>> = {
  'message': I0,
  'messages': I1,
  'bulb': I2,
  'question-mark': I3,
  'pencil': I4,
  'writing': I5,
  'notebook': I6,
  'book': I7,
  'books': I8,
  'news': I9,
  'article': I10,
  'quote': I11,
  'language': I12,
  'mail': I13,
  'send': I14,
  'phone': I15,
  'speakerphone': I16,
  'microphone': I17,
  'clipboard-text': I18,
  'notes': I19,
  'checklist': I20,
  'list-check': I21,
  'calendar': I22,
  'calendar-event': I23,
  'clock': I24,
  'alarm': I25,
  'hourglass': I26,
  'target': I27,
  'flag': I28,
  'trophy': I29,
  'briefcase': I30,
  'building': I31,
  'building-store': I32,
  'presentation': I33,
  'chart-bar': I34,
  'chart-line': I35,
  'chart-pie': I36,
  'report-analytics': I37,
  'table': I38,
  'file-spreadsheet': I39,
  'file-text': I40,
  'files': I41,
  'folder': I42,
  'archive': I43,
  'inbox': I44,
  'stack-2': I45,
  'adjustments': I46,
  'settings': I47,
  'tool': I48,
  'tools': I49,
  'users': I50,
  'user': I51,
  'users-group': I52,
  'heart-handshake': I53,
  'school': I54,
  'certificate': I55,
  'gavel': I56,
  'scale': I57,
  'shield-check': I58,
  'coin': I59,
  'cash': I60,
  'credit-card': I61,
  'receipt': I62,
  'receipt-tax': I63,
  'pig-money': I64,
  'wallet': I65,
  'chart-candle': I66,
  'businessplan': I67,
  'shopping-cart': I68,
  'shopping-bag': I69,
  'gift': I70,
  'tag': I71,
  'discount': I72,
  'building-bank': I73,
  'package': I74,
  'truck-delivery': I75,
  'diamond': I76,
  'code': I77,
  'terminal-2': I78,
  'bug': I79,
  'git-branch': I80,
  'git-pull-request': I81,
  'brand-github': I82,
  'api': I83,
  'database': I84,
  'server': I85,
  'cloud': I86,
  'cpu': I87,
  'device-desktop': I88,
  'device-laptop': I89,
  'device-mobile': I90,
  'device-tablet': I91,
  'device-watch': I92,
  'wifi': I93,
  'router': I94,
  'lock': I95,
  'key': I96,
  'shield': I97,
  'robot': I98,
  'brain': I99,
  'headset': I100,
  'sparkles': I101,
  'wand': I102,
  'puzzle': I103,
  'plug': I104,
  'world': I105,
  'world-www': I106,
  'link': I107,
  'photo': I108,
  'camera': I109,
  'video': I110,
  'movie': I111,
  'palette': I112,
  'brush': I113,
  'typography': I114,
  'layout': I115,
  'color-swatch': I116,
  'vector': I117,
  'bike': I118,
  'run': I119,
  'walk': I120,
  'barbell': I121,
  'swimming': I122,
  'yoga': I123,
  'stretching': I124,
  'trekking': I125,
  'mountain': I126,
  'ball-football': I127,
  'ball-basketball': I128,
  'ball-tennis': I129,
  'golf': I130,
  'heartbeat': I131,
  'heart': I132,
  'stethoscope': I133,
  'pill': I134,
  'dental': I135,
  'eye': I136,
  'bed': I137,
  'moon': I138,
  'zzz': I139,
  'scale-outline': I140,
  'apple': I141,
  'salad': I142,
  'droplet': I143,
  'mood-smile': I144,
  'mood-sad': I145,
  'leaf': I146,
  'flower': I147,
  'tools-kitchen-2': I148,
  'chef-hat': I149,
  'coffee': I150,
  'cup': I151,
  'beer': I152,
  'glass-full': I153,
  'pizza': I154,
  'cake': I155,
  'bread': I156,
  'egg': I157,
  'fish': I158,
  'meat': I159,
  'carrot': I160,
  'home': I161,
  'sofa': I162,
  'armchair': I163,
  'bath': I164,
  'wash-machine': I165,
  'bulb-filled': I166,
  'plant': I167,
  'plant-2': I168,
  'tree': I169,
  'shovel': I170,
  'hammer': I171,
  'paint': I172,
  'ruler': I173,
  'trash': I174,
  'recycle': I175,
  'dog': I176,
  'cat': I177,
  'paw': I178,
  'baby-carriage': I179,
  'shirt': I180,
  'hanger': I181,
  'plane': I182,
  'car': I183,
  'bus': I184,
  'train': I185,
  'ship': I186,
  'gas-station': I187,
  'map': I188,
  'map-pin': I189,
  'route': I190,
  'compass': I191,
  'tent': I192,
  'beach': I193,
  'luggage': I194,
  'e-passport': I195,
  'building-skyscraper': I196,
  'road': I197,
  'parking': I198,
  'steering-wheel': I199,
  'motorbike': I200,
  'scooter': I201,
  'sun': I202,
  'cloud-rain': I203,
  'snowflake': I204,
  'umbrella': I205,
  'temperature': I206,
  'wind': I207,
  'flame': I208,
  'bolt': I209,
  'planet': I210,
  'telescope': I211,
  'music': I212,
  'headphones': I213,
  'guitar-pick': I214,
  'device-gamepad-2': I215,
  'dice': I216,
  'chess': I217,
  'confetti': I218,
  'balloon': I219,
  'ticket': I220,
  'masks-theater': I221,
  'microphone-2': I222,
  'brand-youtube': I223,
  'brand-spotify': I224,
  'device-tv': I225,
  'book-2': I226,
  'pokeball': I227,
  'cards': I228,
  'puzzle-2': I229,
  'flask': I230,
  'atom': I231,
  'dna': I232,
  'math': I233,
  'calculator': I234,
  'abacus': I235,
  'microscope': I236,
  'globe': I237,
  'history': I238,
  'infinity': I239,
  'alert-triangle': I240,
  'info-circle': I241,
  'search': I242,
  'star': I243,
  'bookmark': I244,
  'pin': I245,
  'bell': I246,
  'calendar-heart': I247,
  'cake-roll': I248,
  'christmas-tree': I249,
}
