// Overview glyphs. Tabler, deep-imported per icon so the package tree-shakes
// (AGENTS.md › Gotchas: never hand-draw an icon). Kept apart from chat/icons.ts
// so the two surfaces can change without touching each other.
export { default as IconArrowUp } from '@tabler/icons-react/dist/esm/icons/IconArrowUp.mjs'
export { default as IconArrowRight } from '@tabler/icons-react/dist/esm/icons/IconArrowRight.mjs'
export { default as IconChevronRight } from '@tabler/icons-react/dist/esm/icons/IconChevronRight.mjs'
export { default as IconRefresh } from '@tabler/icons-react/dist/esm/icons/IconRefresh.mjs'
export { default as IconCalendarEvent } from '@tabler/icons-react/dist/esm/icons/IconCalendarEvent.mjs'
export { default as IconChecklist } from '@tabler/icons-react/dist/esm/icons/IconChecklist.mjs'
export { default as IconFlame } from '@tabler/icons-react/dist/esm/icons/IconFlame.mjs'
export { default as IconTarget } from '@tabler/icons-react/dist/esm/icons/IconTarget.mjs'
export { default as IconListCheck } from '@tabler/icons-react/dist/esm/icons/IconListCheck.mjs'
export { default as IconMicrophone2 } from '@tabler/icons-react/dist/esm/icons/IconMicrophone2.mjs'
export { default as IconBrandGithub } from '@tabler/icons-react/dist/esm/icons/IconBrandGithub.mjs'
export { default as IconBrain } from '@tabler/icons-react/dist/esm/icons/IconBrain.mjs'
export { default as IconHistory } from '@tabler/icons-react/dist/esm/icons/IconHistory.mjs'
export { default as IconWand } from '@tabler/icons-react/dist/esm/icons/IconWand.mjs'
export { default as IconSettings } from '@tabler/icons-react/dist/esm/icons/IconSettings.mjs'
export { default as IconInbox } from '@tabler/icons-react/dist/esm/icons/IconInbox.mjs'
export { default as IconAlertTriangle } from '@tabler/icons-react/dist/esm/icons/IconAlertTriangle.mjs'
export { default as IconMapPin } from '@tabler/icons-react/dist/esm/icons/IconMapPin.mjs'
export { default as IconPlus } from '@tabler/icons-react/dist/esm/icons/IconPlus.mjs'
export { default as IconMinus } from '@tabler/icons-react/dist/esm/icons/IconMinus.mjs'
export { default as IconMessageCircle } from '@tabler/icons-react/dist/esm/icons/IconMessageCircle.mjs'
export { default as IconCheck } from '@tabler/icons-react/dist/esm/icons/IconCheck.mjs'
export { default as IconPinned } from '@tabler/icons-react/dist/esm/icons/IconPinned.mjs'
export { default as IconSparkles } from '@tabler/icons-react/dist/esm/icons/IconSparkles.mjs'
export { default as IconClock } from '@tabler/icons-react/dist/esm/icons/IconClock.mjs'
export { default as IconBolt } from '@tabler/icons-react/dist/esm/icons/IconBolt.mjs'
