#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO/.env}"

# todo_cli ARGS... — run todos/cli.mjs from the repo with the .env this wizard is
# writing, so a value saved a few stages ago (TASK_SHEET_ID, …) is visible to it
# in the same run. --env-file-if-exists needs Node 22.9+ (the repo needs 22.13).
todo_cli() {
  (cd "$REPO" && node --env-file-if-exists="$ENV_FILE" todos/cli.mjs "$@")
}

# DRY_RUN=1 prints each todos/cli.mjs call instead of running it.
if [[ "${DRY_RUN:-}" == "1" ]]; then
  todo_cli() { printf '[dry run] node --env-file-if-exists=%s todos/cli.mjs %s\n' "$ENV_FILE" "$*"; }
fi

TOTAL_STAGES=9

banner "Totem todo sources — Action Items sheet + GitHub App"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — project and Sheets API"
say "The Action Items connector reads and writes one Google Sheet as a robot of"
say "its own, not as you. That robot is a service account, and it needs a project"
say "with the Sheets API switched on."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project (a name like 'totem-connectors' is fine), or pick an existing one."
pause "Project ready?"
open_url "https://console.cloud.google.com/apis/library/sheets.googleapis.com"
step "Make sure the project selector at the top shows that project."
step "Click Enable. If it already says 'Manage', it is on already."
pause "Sheets API enabled?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — create the service account"
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts/create"
step "Name it something you will recognise later, e.g. 'totem-action-items'."
step "Click Create and Continue."
step "Skip the optional role and access steps — it needs no project roles at all."
note "Access to the sheet comes from sharing the sheet itself, in stage 4."
step "Click Done."
pause "Service account created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud — download the key, install it here"
step "Open the service account you just made, then the Keys tab."
step "Add key → Create new key → JSON → Create. Your browser downloads a .json file."
pause "Downloaded the JSON key?"
ask GOOGLE_KEY_DOWNLOAD "Path to the downloaded JSON (e.g. ~/Downloads/totem-xxxx.json):"
GOOGLE_KEY_DOWNLOAD="${GOOGLE_KEY_DOWNLOAD/#\~/$HOME}"
if [[ ! -f "$GOOGLE_KEY_DOWNLOAD" ]]; then
  warn "no file at $GOOGLE_KEY_DOWNLOAD"
  SKIPPED+=("Google service-account key — move it to secrets/google-sheets-service-account.json and set GOOGLE_SHEETS_CREDENTIALS_FILE")
else
  mkdir -p "$REPO/secrets"
  GOOGLE_KEY_FILE="$REPO/secrets/google-sheets-service-account.json"
  mv "$GOOGLE_KEY_DOWNLOAD" "$GOOGLE_KEY_FILE"
  chmod 600 "$GOOGLE_KEY_FILE"
  write_env GOOGLE_SHEETS_CREDENTIALS_FILE "$GOOGLE_KEY_FILE"
  SERVICE_ACCOUNT_EMAIL=$(node -e "process.stdout.write(require('$GOOGLE_KEY_FILE').client_email || '')")
  say ""
  say "  Service account address: ${BOLD}${SERVICE_ACCOUNT_EMAIL}${RESET}"
  note "Copy that — the next stage shares the sheet with it."
  pause "Copied?"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Sheets — share your task sheet with the service account"
say "Share ONLY this spreadsheet. The service account should be able to reach"
say "nothing else in Drive."
ask TASK_SHEET_ID "Spreadsheet id (the long part of its URL between /d/ and /edit):"
write_env TASK_SHEET_ID "$TASK_SHEET_ID"
ask TASK_SHEET_ASSIGNEES "Who-column values that mean you, comma-separated (first is used for new rows):"
write_env TASK_SHEET_ASSIGNEES "$TASK_SHEET_ASSIGNEES"
# Also in this shell's environment, for anything that does not read .env itself.
export TASK_SHEET_ID TASK_SHEET_ASSIGNEES
open_url "https://docs.google.com/spreadsheets/d/${TASK_SHEET_ID}/edit"
step "Click Share."
step "Paste the service account address from the last stage."
step "Set it to Editor — the connector writes status and its own id column back."
step "Untick 'Notify people' (it is a robot), then Share."
pause "Shared as Editor?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Action Items — verify and bootstrap the columns"
say "Now Totem reads the sheet for real, then adds its two connector columns"
say "(visible 'Tag' and hidden 'Totem ID') if they are not there yet."
if [[ -n "${GOOGLE_KEY_FILE:-}" ]]; then
  if todo_cli sheet-inspect --credentials "$GOOGLE_KEY_FILE"; then
    say ""
    if confirm "Read the sheet. Bootstrap the connector columns now?"; then
      todo_cli sheet-bootstrap-schema \
        --credentials "$GOOGLE_KEY_FILE" \
        --confirm-sheet-id "$TASK_SHEET_ID" \
        || SKIPPED+=("sheet bootstrap — re-run: node todos/cli.mjs sheet-bootstrap-schema --confirm-sheet-id $TASK_SHEET_ID")
    fi
  else
    warn "could not read the sheet — check the share in stage 4, then re-run this wizard"
    SKIPPED+=("Action Items verification — node todos/cli.mjs sheet-inspect")
  fi
else
  warn "no credentials file, skipping verification"
fi
pause "Continue to GitHub?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GitHub — create the App"
say "This replaces the gh CLI. The App's reach is exactly the repositories you"
say "install it on, and Totem mints its own hour-long tokens from a key file —"
say "no login on this machine, nothing to re-authorise."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: something unique, e.g. 'Totem Tasks (your-login)'."
step "Homepage URL: your GitHub profile URL — anything valid works."
step "Under Webhook, UNTICK Active. Totem polls; it needs no webhook."
step "Repository permissions → Issues: Read and write."
step "Repository permissions → Metadata: Read-only (GitHub selects this for you)."
note "Those two are all it needs. Leave every other permission at No access."
step "Where can this App be installed: Only on this account."
step "Click Create GitHub App."
pause "App created?"
step "On the App's General page, find 'App ID' near the top."
ask GITHUB_APP_ID "Paste the App ID (a number):"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub — private key"
step "Still on the App's General page, scroll to 'Private keys'."
step "Click Generate a private key. Your browser downloads a .pem file."
note "GitHub shows this once. If you lose it, generate another and re-run this stage."
pause "Downloaded the .pem?"
ask GITHUB_KEY_DOWNLOAD "Path to the downloaded .pem (e.g. ~/Downloads/totem-tasks.private-key.pem):"
GITHUB_KEY_DOWNLOAD="${GITHUB_KEY_DOWNLOAD/#\~/$HOME}"
if [[ ! -f "$GITHUB_KEY_DOWNLOAD" ]]; then
  warn "no file at $GITHUB_KEY_DOWNLOAD"
  SKIPPED+=("GitHub App private key — move it to secrets/github-app.pem and set GITHUB_APP_PRIVATE_KEY_FILE")
else
  mkdir -p "$REPO/secrets"
  GITHUB_KEY_FILE="$REPO/secrets/github-app.pem"
  mv "$GITHUB_KEY_DOWNLOAD" "$GITHUB_KEY_FILE"
  chmod 600 "$GITHUB_KEY_FILE"
  write_env GITHUB_APP_PRIVATE_KEY_FILE "$GITHUB_KEY_FILE"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "GitHub — install the App on your repositories"
say "An App with no installation can see nothing at all. This is the step that"
say "decides which repositories Totem may read issues from."
open_url "https://github.com/settings/apps"
step "Open the App you just created, then its 'Install App' tab."
step "Click Install next to your account."
step "Choose All repositories, or Only select repositories and pick the ones you"
step "  actually track tasks in."
step "Click Install."
pause "Installed?"
# Offer the login gh is signed in as, if any; there is no built-in default.
GH_LOGIN=$(gh api user --jq .login 2>/dev/null || true)
ask GITHUB_ASSIGNEE_LOGIN "Your GitHub login, for 'assigned to me' searches${GH_LOGIN:+ [$GH_LOGIN]}:"
GITHUB_ASSIGNEE_LOGIN="${GITHUB_ASSIGNEE_LOGIN:-$GH_LOGIN}"
write_env GITHUB_ASSIGNEE_LOGIN "$GITHUB_ASSIGNEE_LOGIN"
note "An installation token is not a person, so the search needs the login spelled out."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub — verify, then restart the bridge"
if [[ -n "${GITHUB_KEY_FILE:-}" && -n "${GITHUB_APP_ID:-}" ]]; then
  if todo_cli github-check \
      --app-id "$GITHUB_APP_ID" \
      --private-key "$GITHUB_KEY_FILE" \
      --assignee "$GITHUB_ASSIGNEE_LOGIN"; then
    say ""
    say "That is a real installation token, minted just now."
  else
    warn "the App could not be used — check the install in stage 8"
    SKIPPED+=("GitHub App verification — node todos/cli.mjs github-check")
  fi
else
  warn "missing App id or key file, skipping verification"
fi
say ""
if confirm "Restart the bridge so it picks up the new credentials?"; then
  systemctl --user restart assistant-bridge.service \
    && say "Restarted. The startup log will say which GitHub client it chose." \
    || SKIPPED+=("bridge restart — systemctl --user restart assistant-bridge.service")
else
  SKIPPED+=("bridge restart — systemctl --user restart assistant-bridge.service")
fi

finish
