import React, { useState } from 'react'
import { purgeDeletedTodos, restoreBoardTodo, updateTodoPreferences } from '../api'
import type { Todo, TodoPreferences } from './types'

interface Props { snoozed: Todo[]; deleted: Todo[]; preferences?: TodoPreferences; onRestore?: (id: string) => Promise<void>; onChanged?: () => void }

export default function TodoLifecyclePanels({ snoozed, deleted, preferences = { autoArchiveDays: null, autoArchiveAt: null, recyclePurgeDays: null }, onRestore, onChanged }: Props) {
  const [open, setOpen] = useState<'snoozed' | 'deleted' | 'settings' | null>(null)
  const [prefs, setPrefs] = useState(preferences)
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  async function restore(id: string) { try { if (onRestore) await onRestore(id); else await restoreBoardTodo(id); onChanged?.() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Task could not be restored.') } }
  async function purge() { try { const days = prefs.recyclePurgeDays ?? 30; const olderThan = new Date(Date.now() - days * 86_400_000).toISOString(); const result = await purgeDeletedTodos(olderThan); setNotice(`Backed up the task database and purged ${result.purged.toLocaleString()} task${result.purged === 1 ? '' : 's'}.`); onChanged?.() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Recycle bin could not be purged.') } }
  return <div className="todo-lifecycle"><div className="todo-lifecycle-bar"><button onClick={() => setOpen(open === 'snoozed' ? null : 'snoozed')}>{snoozed.length.toLocaleString()} snoozed task{snoozed.length === 1 ? '' : 's'}</button><button onClick={() => setOpen(open === 'deleted' ? null : 'deleted')}>Recycle bin · {deleted.length.toLocaleString()}</button><button onClick={() => setOpen(open === 'settings' ? null : 'settings')}>Retention</button></div>{error && <div className="todo-inline-error">{error}</div>}{notice && <div className="todo-inline-notice">{notice}</div>}{open === 'snoozed' && <section className="todo-lifecycle-panel"><h3>Snoozed</h3>{snoozed.length ? snoozed.map(todo => <div key={todo.id}><span>{todo.title}</span><time>{todo.snoozedUntil ? new Date(todo.snoozedUntil).toLocaleString() : ''}</time></div>) : <p>No snoozed tasks.</p>}</section>}{open === 'deleted' && <section className="todo-lifecycle-panel"><h3>Recycle bin</h3>{deleted.map(todo => <div key={todo.id}><span>{todo.title}</span><button className="btn" aria-label={`Restore ${todo.title}`} onClick={() => void restore(todo.id)}>Restore</button></div>)}{deleted.length > 0 && <button className="btn danger" onClick={() => void purge()}>Purge eligible deleted tasks</button>}</section>}{open === 'settings' && <section className="todo-lifecycle-panel"><h3>Retention</h3><label className="field"><span>Archive completed tasks daily at</span><input type="time" value={prefs.autoArchiveAt ?? ''} onChange={event => setPrefs(current => ({ ...current, autoArchiveAt: event.target.value || null }))} /></label><label className="field"><span>Archive completed after days</span><input type="number" min="1" value={prefs.autoArchiveDays ?? ''} onChange={event => setPrefs(current => ({ ...current, autoArchiveDays: event.target.value ? Number(event.target.value) : null }))} /></label><label className="field"><span>Purge recycle bin after days</span><input type="number" min="1" value={prefs.recyclePurgeDays ?? ''} onChange={event => setPrefs(current => ({ ...current, recyclePurgeDays: event.target.value ? Number(event.target.value) : null }))} /></label><button className="btn" onClick={() => void updateTodoPreferences(prefs).then(() => setNotice('Retention settings saved.')).catch(cause => setError(cause.message))}>Save retention</button></section>}</div>
}
